import { TaskItem } from "@/types/interface";

export const ALL_TAGS: Array<string> = [
  "BEC",
  "Banking",
  "CEO",
  "User account",
  "Data Protection",
] as const;

export const ITEMS_PER_PAGE = 5;
export const TAGS_PARAM = "tags" as const;
export const TAG_STYLES: Record<string, { bg: string; text: string }> = {
  BEC: { bg: "bg-blue-100", text: "text-blue-700" },
  Banking: { bg: "bg-orange-100", text: "text-orange-700" },
  CEO: { bg: "bg-yellow-100", text: "text-yellow-700" },
  "User account": { bg: "bg-indigo-100", text: "text-indigo-700" },
  "Data Protection": { bg: "bg-indigo-100", text: "text-indigo-700" },
} as const;

export const sampleData: TaskItem[] = [
  {
    id: "1",
    name: "Fix login authentication bug",
    description: "Users are getting logged out randomly during sessions",
    tags: ["BEC", "User account"],
    date: "2024-03-10",
    contain: "Sarah Chen",
    level: "In Progress",
  },
  {
    id: "2",
    name: "Implement dark mode",
    description: "Add dark mode support across all pages",
    tags: ["Banking", "User account"],
    date: "2024-03-11",
    contain: "Mike Johnson",
    level: "Pending Review",
  },
  {
    id: "3",
    name: "Optimize database queries",
    description: "Improve performance of main dashboard queries",
    tags: ["BEC", "Banking"],
    date: "2024-03-12",
    contain: "David Kim",
    level: "In Progress",
  },
  {
    id: "4",
    name: "Update API documentation",
    description: "Add new endpoints and update existing documentation",
    tags: ["Data Protection", "Banking"],
    date: "2024-03-13",
    contain: "Emma Wilson",
    level: "Completed",
  },
  {
    id: "5",
    name: "Security audit implementation",
    description: "Implement security recommendations from recent audit",
    tags: ["Data Protection", "CEO"],
    date: "2024-03-14",
    contain: "Alex Martinez",
    level: "In Progress",
  },
  {
    id: "6",
    name: "Redesign user dashboard",
    description: "Implement new dashboard design from Figma",
    tags: ["User account", "CEO"],
    date: "2024-03-15",
    contain: "Lisa Park",
    level: "Development",
  },
  {
    id: "7",
    name: "Refactor authentication service",
    description: "Technical debt cleanup in auth service",
    tags: ["BEC", "Data Protection"],
    date: "2024-03-16",
    contain: "Chris Taylor",
    level: "Pending Review",
  },
  {
    id: "8",
    name: "Implement email notifications",
    description: "Add email notifications for important events",
    tags: ["Banking", "CEO"],
    date: "2024-03-17",
    contain: "James Wilson",
    level: "Blocked",
  },
  {
    id: "9",
    name: "Mobile responsive design",
    description: "Ensure all pages work well on mobile devices",
    tags: ["User account", "BEC"],
    date: "2024-03-18",
    contain: "Nina Patel",
    level: "In Progress",
  },
  {
    id: "10",
    name: "Setup staging environment",
    description: "Configure new staging environment for testing",
    tags: ["Data Protection", "Banking"],
    date: "2024-03-19",
    contain: "Tom Anderson",
    level: "On Hold",
  },
  {
    id: "11",
    name: "Update banking integration API",
    description: "Implement new banking partners API requirements",
    tags: ["Banking", "BEC"],
    date: "2024-03-20",
    contain: "Rachel Myers",
    level: "In Progress",
  },
  {
    id: "12",
    name: "Executive dashboard enhancement",
    description: "Add new metrics and KPIs for executive view",
    tags: ["CEO", "Banking"],
    date: "2024-03-21",
    contain: "Jordan Lee",
    level: "Development",
  },
  {
    id: "13",
    name: "User data encryption upgrade",
    description: "Implement advanced encryption for user data",
    tags: ["Data Protection", "User account"],
    date: "2024-03-22",
    contain: "Sophia Rodriguez",
    level: "Pending Review",
  },
  {
    id: "14",
    name: "BEC prevention system",
    description: "Implement new security measures for BEC prevention",
    tags: ["BEC", "Data Protection"],
    date: "2024-03-23",
    contain: "Marcus Johnson",
    level: "In Progress",
  },
  {
    id: "15",
    name: "Account recovery process",
    description: "Streamline user account recovery workflow",
    tags: ["User account", "Data Protection"],
    date: "2024-03-24",
    contain: "Emily Chen",
    level: "Completed",
  },
  {
    id: "16",
    name: "Banking dashboard redesign",
    description: "Modernize banking interface and improve UX",
    tags: ["Banking", "User account"],
    date: "2024-03-25",
    contain: "Kevin Park",
    level: "Development",
  },
  {
    id: "17",
    name: "Executive reporting system",
    description: "Automated report generation for executive team",
    tags: ["CEO", "Data Protection"],
    date: "2024-03-26",
    contain: "Linda Martinez",
    level: "Blocked",
  },
  {
    id: "18",
    name: "Fraud detection enhancement",
    description: "Improve BEC and fraud detection algorithms",
    tags: ["BEC", "Banking"],
    date: "2024-03-27",
    contain: "Ryan Thompson",
    level: "In Progress",
  },
  {
    id: "19",
    name: "User preference center",
    description: "New interface for managing user preferences",
    tags: ["User account", "CEO"],
    date: "2024-03-28",
    contain: "Diana Kim",
    level: "Pending Review",
  },
  {
    id: "20",
    name: "Compliance monitoring system",
    description: "Automated compliance checking for banking operations",
    tags: ["Banking", "Data Protection"],
    date: "2024-03-29",
    contain: "Michael Chen",
    level: "On Hold",
  },
  {
    id: "21",
    name: "Executive mobile app",
    description: "Dedicated mobile app for executive team",
    tags: ["CEO", "User account"],
    date: "2024-03-30",
    contain: "Jessica Wong",
    level: "Development",
  },
  {
    id: "22",
    name: "Security policy enforcement",
    description: "Implement new security policies across platform",
    tags: ["Data Protection", "BEC"],
    date: "2024-03-31",
    contain: "Andrew Davis",
    level: "In Progress",
  },
  {
    id: "23",
    name: "Transaction monitoring",
    description: "Enhanced monitoring system for banking transactions",
    tags: ["Banking", "Data Protection"],
    date: "2024-04-01",
    contain: "Steven Lee",
    level: "Pending Review",
  },
  {
    id: "24",
    name: "User activity analytics",
    description: "Implement detailed user activity tracking",
    tags: ["User account", "BEC"],
    date: "2024-04-02",
    contain: "Maria Garcia",
    level: "Development",
  },
  {
    id: "25",
    name: "Executive communication portal",
    description: "Secure communication platform for executives",
    tags: ["CEO", "Data Protection"],
    date: "2024-04-03",
    contain: "Paul Anderson",
    level: "Blocked",
  },
  {
    id: "26",
    name: "Authentication system upgrade",
    description: "Implement biometric authentication",
    tags: ["User account", "Data Protection"],
    date: "2024-04-04",
    contain: "Karen Wilson",
    level: "In Progress",
  },
  {
    id: "27",
    name: "Banking API security",
    description: "Enhance security measures for banking APIs",
    tags: ["Banking", "BEC"],
    date: "2024-04-05",
    contain: "Daniel Kim",
    level: "Development",
  },
  {
    id: "28",
    name: "Executive data analytics",
    description: "Advanced analytics dashboard for executive team",
    tags: ["CEO", "Banking"],
    date: "2024-04-06",
    contain: "Michelle Lee",
    level: "Pending Review",
  },
  {
    id: "29",
    name: "User permissions system",
    description: "Granular control over user permissions",
    tags: ["User account", "Data Protection"],
    date: "2024-04-07",
    contain: "Brian Taylor",
    level: "Completed",
  },
  {
    id: "30",
    name: "Threat detection system",
    description: "AI-powered threat detection for BEC prevention",
    tags: ["BEC", "Data Protection"],
    date: "2024-04-08",
    contain: "Jennifer Martinez",
    level: "In Progress",
  },
];
